Update pre-commit structure to version 4.0.0
[#625625414772799]

diff --git a/dev/git-hooks/pre-commit b/dev/git-hooks/pre-commit
--- a/dev/git-hooks/pre-commit
+++ b/dev/git-hooks/pre-commit
@@ -2,12 +2,15 @@
 
 #######################################################################################
 #
-# This script is setup for PHP 7.0 AND 8.0 and submodules
-# Change the PHP version is desired.
+# Test our code against various unit test systems and linters and prevent commit
+# if any of them fail.
+#
+# @notice Customized to support multiple versions of PHP is same runs.
+# @notice Customized to run unit tests from PRO version.
 #
 # @see /dev/git-hooks.sh for installation as symbolic link
 #
-# @version 2.2.0
+# @version 4.0.0
 #
 #####################################################################################
 GREEN="$(tput setaf 2)"
@@ -16,6 +19,9 @@ YELLOW="$(tput setaf 3)"
 RED="$(tput setaf 1)"
 BLUE="$(tput setaf 6)"
 RESET_COLOR="$(tput sgr0)"
+
+PHPCS='phpcs 8.0'
+PHPSTAN='phpstan 8.0'
 
 PROJECT="."
 ## Fix windows paths
@@ -42,85 +48,85 @@ function php_units() {
 }
 
 function php_unit() {
-	if [[ "$PHP_FILES" ]]; then
-		if [[ ! -f ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml ]]; then
-			echo "${YELLOW}[pre-commit]${RED} ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml not found! (Probably not setup yet!).${WHITE}"
-		else
-			# Run phpunit.
-			echo "${YELLOW}[pre-commit]${BLUE} Running ${1}... ${WHITE}"
-			OUTPUT=$(${1} --configuration ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml)
-			if [[ $? != 0 ]]; then
-				echo
-				echo "${BLUE}PHP Unit Failed! Fix the error before commit!"
-				echo "${RED}$OUTPUT"
-				exit_reset_colors
-			fi
-			echo "${YELLOW}[pre-commit]${GREEN} ${1} Tests Passed!${WHITE}"
-		fi
-	fi
+   	if [[ "$PHP_FILES" ]]; then
+   		if [[ ! -f ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml.dist ]]; then
+   			echo "${YELLOW}[pre-commit]${RED} ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml.dist not found! (Probably not setup yet!).${WHITE}"
+   		else
+   			# Run phpunit.
+   			echo "${YELLOW}[pre-commit]${BLUE} Running ${1}... ${WHITE}"
+   			OUTPUT=$(${1} --configuration ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml.dist)
+   			if [[ $? != 0 ]]; then
+   				echo
+   				echo "${BLUE}${1} Failed! Fix the error before commit!"
+   				echo "${RED}$OUTPUT"
+   				exit_reset_colors
+   			fi
+   			echo "${YELLOW}[pre-commit]${GREEN} ${1} Tests Passed!${WHITE}"
+   		fi
+   	fi
 }
 php_units &
 
 function php_lint() {
-	if [[ "$PHP_FILES" ]]; then
-		# Run php lint.
-		echo "${YELLOW}[pre-commit]${BLUE} Checking ${1} Lint... ${WHITE}"
-		for FILE in ${PHP_FILES}; do
-			OUTPUT=$(${1} -l -d display_errors=0 ${PROJECT}/${FILE})
-			if [[ $? != 0 ]]; then
-				echo
-				echo "${BLUE}PHP Lint Failed. Fix the error before commit."
-				echo "${RED}$OUTPUT"
-				exit_reset_colors
-			fi
-		done
-		echo "${YELLOW}[pre-commit]${GREEN} ${1} Lint Passed!${WHITE}"
-	fi
+    if [[ "$PHP_FILES" ]]; then
+        # Run php lint.
+        echo "${YELLOW}[pre-commit]${BLUE} Checking ${1} Lint... ${WHITE}"
+        for FILE in ${PHP_FILES}; do
+            OUTPUT=$(${1} -l -d display_errors=0 ${PROJECT}/${FILE})
+            if [[ $? != 0 ]]; then
+                echo
+                echo "${BLUE}PHP Lint Failed. Fix the error before commit."
+                echo "${RED}$OUTPUT"
+                exit_reset_colors
+            fi
+        done
+        echo "${YELLOW}[pre-commit]${GREEN} ${1} Lint Passed!${WHITE}"
+    fi
 }
 php_lint 'php 7.0' &
 php_lint 'php 8.0' &
 
 function php_code_sniffer() {
-	if [[ "$PHP_FILES" != "" ]]; then
-		# Check for phpcs config
-		if [[ ! -f ${PROJECT}/phpcs.xml ]] && [[ ! -f ${PROJECT}/phpcs.xml.dist ]]; then
-			echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/phpcs.xml or ${PROJECT}/phpcs.xml.dist not found!"
-			exit_reset_colors
-		fi
-		for FILE in ${PHP_FILES}; do
-			FILES="$FILES ${PROJECT}/${FILE}"
-		done
-		echo "${YELLOW}[pre-commit]${BLUE} Running PHPCS... ${WHITE}"
-		OUTPUT=$(phpcs --encoding=utf-8 -s -n -p ${FILES})
-		if [[ $? != 0 ]]; then
-			echo
-			echo "${BLUE}PHPCS failed. Fix the error before commit!"
-			echo "${RED}$OUTPUT"
-			echo
-			echo "${YELLOW}For automatic fixes run"
-			echo
-			echo "${WHITE}phpcbf $FILES"
-			echo
-			exit_reset_colors
-		fi
-		echo "${YELLOW}[pre-commit]${GREEN} PHPCS Passed!${WHITE}"
-	fi
+    if [[ "$PHP_FILES" != "" ]]; then
+        # Check for phpcs config
+        if [[ ! -f ${PROJECT}/phpcs.xml ]] && [[ ! -f ${PROJECT}/phpcs.xml.dist ]]; then
+            echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/phpcs.xml or ${PROJECT}/phpcs.xml.dist not found!"
+            exit_reset_colors
+        fi
+        for FILE in ${PHP_FILES}; do
+            FILES="$FILES ${PROJECT}/${FILE}"
+        done
+        echo "${YELLOW}[pre-commit]${BLUE} Running PHPCS... ${WHITE}"
+        OUTPUT=$(${PHPCS} --encoding=utf-8 -s -n -p ${FILES})
+        if [[ $? != 0 ]]; then
+            echo
+            echo "${BLUE}PHPCS failed. Fix the error before commit!"
+            echo "${RED}$OUTPUT"
+            echo
+            echo "${YELLOW}For automatic fixes run"
+            echo
+            echo "${WHITE}phpcbf $FILES"
+            echo
+            exit_reset_colors
+        fi
+        echo "${YELLOW}[pre-commit]${GREEN} PHPCS Passed!${WHITE}"
+    fi
 }
 php_code_sniffer &
 
 function php_stan() {
-	if [[ "$PHP_FILES" ]]; then
-		# Run phpstan.
-		echo "${YELLOW}[pre-commit]${BLUE} Running PHP Stan... ${WHITE}"
-		OUTPUT=$(phpstan analyse --memory-limit=2G)
-		if [[ $? != 0 ]]; then
-			echo
-			echo "${BLUE}PHP Stan Failed. Fix the error before commit."
-			echo "${RED}$OUTPUT"
-			exit_reset_colors
-		fi
-		echo "${YELLOW}[pre-commit]${GREEN} PHP Stan Passed!${WHITE}"
-	fi
+    if [[ "$PHP_FILES" ]]; then
+        # Run phpstan.
+        echo "${YELLOW}[pre-commit]${BLUE} Running PHP Stan... ${WHITE}"
+        OUTPUT=$(${PHPSTAN} analyse --memory-limit=2G)
+        if [[ $? != 0 ]]; then
+            echo
+            echo "${BLUE}PHP Stan Failed. Fix the error before commit."
+            echo "${RED}$OUTPUT"
+            exit_reset_colors
+        fi
+        echo "${YELLOW}[pre-commit]${GREEN} PHP Stan Passed!${WHITE}"
+    fi
 }
 php_stan &
 
@@ -128,14 +134,14 @@ php_stan &
 # If it sent exit code 1, it failed and the result from `wait` will be false.
 FAIL=0
 for job in $(jobs -p); do
-	wait $job || let "FAIL+=1"
+    wait "$job" || (( FAIL+=1 ))
 done
 
-echo ${RESET_COLOR}
+echo "${RESET_COLOR}"
 
 # If any of the background tasks failed, we exit 1
 if [[ $FAIL -ne 0 ]]; then
-	exit 1
+    exit 1
 else
-	exit 0
+    exit 0
 fi
