Refactor pre-commit to modern ASYNC with labels structure

diff --git a/dev/git-hooks/pre-commit b/dev/git-hooks/pre-commit
--- a/dev/git-hooks/pre-commit
+++ b/dev/git-hooks/pre-commit
@@ -1,84 +1,125 @@
-#!/bin/sh
+#!/bin/bash
 
 #######################################################################################
 #
-# This script is setup for PHP 5.6 and PHP 7.4
+# This script is setup for PHP 5.6 AND 7.4 and submodules
+# Change the PHP version is desired.
 #
-#######################################################################################
+# @see /dev/git-hooks.sh for installation as symbolic link
+#
+# @version 2.0.0
+#
+#####################################################################################
+GREEN="$(tput setaf 2)"
+WHITE="$(tput setaf 7)"
+YELLOW="$(tput setaf 3)"
+RED="$(tput setaf 1)"
+BLUE="$(tput setaf 6)"
+RESET_COLOR="$(tput sgr0)"
+
 PROJECT="."
-
 ## Fix windows paths
 PROJECT=${PROJECT//\\//}
 
-STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
-
-# Check for phpcs config
-if [[ ! -f ${PROJECT}/phpcs.xml ]] && [[ ! -f ${PROJECT}/phpcs.xml.dist ]]; then
-  echo "${PROJECT}/phpcs.xml or ${PROJECT}/phpcs.xml.dist not found!"
-  exit 1;
+PHP_FILES=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\.php)
+if [[ ! "$PHP_FILES" ]]; then
+	echo "${YELLOW}[pre-commit]${BLUE} No Testable Files Changed ${RESET_COLOR}"
+	exit 0
+fi
+if [[ ! "$PHP_FILES" ]]; then
+	echo "${YELLOW}[pre-commit]${BLUE} No PHP Files Changed ${WHITE}"
 fi
 
-# Run phpunit (PHP5).
-## Use SSH script instead of a PHP call so no $PHP
-echo "Running PHP Unit (PHP5.6)."
-phpunit 5.6 --configuration ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml
-if [[ $? != 0 ]]; then
-  echo "Fix the error before commit!"
-  exit 1
-fi
+function exit_reset_colors() {
+	echo ${RESET_COLOR}
+	exit 1
+}
 
-# Run phpunit (PHP7).
-echo "Running PHP Unit (PHP7)."
-phpunit 7.4 --configuration ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml
-if [[ $? != 0 ]]; then
-  echo "Fix the error before commit!"
-  exit 1
-fi
+# Must run them consecutively to prevent conflicts.
+function php_units() {
+	php_unit 'phpunit 5.6'
+	php_unit 'phpunit 7.4'
+}
 
+function php_unit() {
+	if [[ "$PHP_FILES" ]]; then
+		if [[ ! -f ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml ]]; then
+			echo "${YELLOW}[pre-commit]${RED} ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml not found! (Probably not setup yet!).${WHITE}"
+		else
+			# Run phpunit.
+			echo "${YELLOW}[pre-commit]${BLUE} Running ${1}... ${WHITE}"
+			OUTPUT=$(${1} --configuration ../advanced-sidebar-menu-pro/dev/wp-unit/phpunit.xml)
+			if [[ $? != 0 ]]; then
+				echo
+				echo "${BLUE}PHP Unit Failed! Fix the error before commit!"
+				echo "${RED}$OUTPUT"
+				exit_reset_colors
+			fi
+			echo "${YELLOW}[pre-commit]${GREEN} ${1} Tests Passed!${WHITE}"
+		fi
+	fi
+}
+php_units &
 
-# Determine if a file list is passed.
-if [[ "$#" -eq 1 ]]; then
-  oIFS=$IFS
-  IFS='
-  '
-  SFILES="$1"
-  IFS=${oIFS}
-fi
-SFILES=${SFILES:-$STAGED_FILES_CMD}
+function php_lint() {
+	if [[ "$PHP_FILES" ]]; then
+		# Run php lint.
+		echo "${YELLOW}[pre-commit]${BLUE} Checking ${1} Lint... ${WHITE}"
+		for FILE in ${PHP_FILES}; do
+			OUTPUT=$(${1} -l -d display_errors=0 ${PROJECT}/${FILE})
+			if [[ $? != 0 ]]; then
+				echo
+				echo "${BLUE}PHP Lint Failed. Fix the error before commit."
+				echo "${RED}$OUTPUT"
+				exit_reset_colors
+			fi
+		done
+		echo "${YELLOW}[pre-commit]${GREEN} ${1} Lint Passed!${WHITE}"
+	fi
+}
+php_lint 'php 5.6' &
+php_lint 'php 7.4' &
 
-# Run php lint (PHP5).
-echo "Checking PHP5.6 Lint..."
-for FILE in ${SFILES}; do
-  php 5.6 -l -d display_errors=0 ${PROJECT}/${FILE}
-  if [[ $? != 0 ]]; then
-    echo "Fix the error before commit."
-    exit 1
-  fi
-  FILES="${FILES} ${PROJECT}/${FILE}"
+function php_code_sniffer() {
+	if [[ "$PHP_FILES" != "" ]]; then
+		# Check for phpcs config
+		if [[ ! -f ${PROJECT}/phpcs.xml ]] && [[ ! -f ${PROJECT}/phpcs.xml.dist ]]; then
+			echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/phpcs.xml or ${PROJECT}/phpcs.xml.dist not found!"
+			exit_reset_colors
+		fi
+		for FILE in ${PHP_FILES}; do
+			FILES="$FILES ${PROJECT}/${FILE}"
+		done
+		echo "${YELLOW}[pre-commit]${BLUE} Running PHPCS... ${WHITE}"
+		OUTPUT=$(phpcs --encoding=utf-8 -s -n -p ${FILES})
+		if [[ $? != 0 ]]; then
+			echo
+			echo "${BLUE}PHPCS failed. Fix the error before commit!"
+			echo "${RED}$OUTPUT"
+			echo
+			echo "${YELLOW}For automatic fixes run"
+			echo
+			echo "${WHITE}phpcbf $FILES"
+			echo
+			exit_reset_colors
+		fi
+		echo "${YELLOW}[pre-commit]${GREEN} PHPCS Passed!${WHITE}"
+	fi
+}
+php_code_sniffer &
+
+# Go through each background task
+# If it sent exit code 1, it failed and the result from `wait` will be false.
+FAIL=0
+for job in $(jobs -p); do
+	wait $job || let "FAIL+=1"
 done
 
-# Run php lint (PHP7).
-echo "Checking PHP7 Lint..."
-for FILE in ${SFILES}; do
-  php 7.4 -l -d display_errors=0 ${PROJECT}/${FILE}
-  if [[ $? != 0 ]]; then
-    echo "Fix the error before commit."
-    exit 1
-  fi
-  FILES="${FILES} ${PROJECT}/${FILE}"
-done
+echo ${RESET_COLOR}
 
-# Run phpcs.
-if [[ "${FILES}" != "" ]]; then
-  echo "Running Code Sniffer..."
-  phpcs --encoding=utf-8 -s -n -p ${FILES}
-  if [[ $? != 0 ]]; then
-    echo "Fix the error before commit!"
-    echo "Run"
-    echo "  phpcbf ${FILES}"
-    echo "for automatic fix or fix it manually."
-    exit 1
-  fi
+# If any of the background tasks failed, we exit 1
+if [[ $FAIL -ne 0 ]]; then
+	exit 1
+else
+	exit 0
 fi
-
-exit $?
